[build-system]
requires = [ "setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = '--doctest-modules --doctest-glob="*.rst" --cov=openpile'
testpaths = [
    "test", "docs/source",
] 

[tool.black]
line-length = 100
